/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Comp3111Project;
import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;




public class LibraryTest {
	//LibraryFunction

	@Test 
	public void checkGetInputResult() {
		assertEquals(1, LibraryFunction.checkForValidInput("Sam, Wong"));
		assertEquals(-1, LibraryFunction.checkForValidInput("Sam121Wong"));
		assertEquals(-1, LibraryFunction.checkForValidInput("154546"));
		assertEquals(0, LibraryFunction.checkForValidInput("12345678"));
	}
	
	@Test 
	public void checkFormat() {
		assertEquals(1, LibraryFunction.checkForFormat("Sam, Wong"));
		assertEquals(-1, LibraryFunction.checkForValidInput(",..Sam, Wong"));
	}
	
}
